# .github/release-drafter.yml
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

template: |
  ## Cambios en esta versión
  $CHANGES

categories:
  - title: "🚀 Nuevas Funcionalidades"
    labels: ["enhancement", "feat"]
  - title: "🐛 Bug Fixes"
    labels: ["bug", "fix"]
  - title: "📦 Otros cambios"
    labels: ["chore", "deps", "documentation"]

version-resolver:
  major:
    labels: ["breaking-change"]
  minor:
    labels: ["enhancement", "feat"]
  patch:
    labels: ["bug", "fix", "chore", "deps"]

exclude-labels: ["skip-changelog"]